name: pipeline-ecr-ebs

on:
  push:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  MODULE_NAME: ${{ vars.MODULE_NAME }}
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Login no ECR, build e push da imagem Docker

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Configura o EB CLI e executa o deploy
