name: pipeline-backend-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instala dependências do backend
        run: npm --prefix backend install

      - name: Executa os testes
        run: npm --prefix backend test -- --testPathIgnorePatterns=backend/src/products/products.service.spec.ts
