name: Destroy ECR & EB
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION:            ${{ vars.AWS_REGION }}
      AWS_ACCOUNT_ID:        ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_S3:             ${{ vars.BUCKET_S3 }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: |
          terraform -chdir=.environment init \
            -backend-config="bucket=${{ env.BUCKET_S3 }}" \
            -backend-config="key=state/terraform.tfstate"
      - run: terraform -chdir=.environment destroy -var-file=terraform.tfvars -auto-approve