name: deploy-to-eb

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Verifica arquivos esperados
        run: |
          ls -l frontend/.elasticbeanstalk/config.yml || echo "Arquivo config.yml não encontrado"
          ls -l frontend/Dockerrun.aws.json || echo "Arquivo Dockerrun.aws.json não encontrado"

      - name: Faz upload dos arquivos para uso no deploy
        uses: actions/upload-artifact@v4
        with:
          name: ebconfig
          path: |
            frontend/.elasticbeanstalk/config.yml
            frontend/Dockerrun.aws.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Baixa os artefatos
        uses: actions/download-artifact@v4
        with:
          name: ebconfig
          path: .

      - name: Substitui variáveis no Dockerrun.aws.json
        run: |
          sed -i "s|<AWS_ACCOUNT_ID>|${{ secrets.AWS_ACCOUNT_ID }}|" Dockerrun.aws.json
          sed -i "s|<PROJECT_NAME>|conchayoro|" Dockerrun.aws.json
          sed -i "s|<MODULE_NAME>|frontend|" Dockerrun.aws.json
          sed -i "s|<TAG>|latest|" Dockerrun.aws.json

      - name: Instala Python e a EB CLI
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - run: |
          pip install --upgrade pip
          pip install awsebcli

      - name: Realiza o deploy com EB CLI
        run: eb deploy --verbose
