name: pipeline-ecr-ebs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/upload-artifact@v4
        with:
          name: ebconfig
          path: |
            frontend/.elasticbeanstalk/config.yml
            frontend/Dockerrun.aws.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ebconfig
          path: .

      - run: sed -i "s|<AWS_ACCOUNT_ID>|${{ secrets.AWS_ACCOUNT_ID }}|" Dockerrun.aws.json
      - run: sed -i "s|<PROJECT_NAME>|conchayoro|" Dockerrun.aws.json
      - run: sed -i "s|<MODULE_NAME>|frontend|" Dockerrun.aws.json
      - run: sed -i "s|<TAG>|latest|" Dockerrun.aws.json

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - run: python -m pip install --upgrade pip && pip install awsebcli

      - run: eb deploy --verbose
