name: pipeline-ecr-ebs

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login no ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Build e push da imagem Docker
        run: |
          docker build -t frontend:latest .
          docker tag frontend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/conchayoro/frontend:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/conchayoro/frontend:latest

      - name: Salva arquivos para o deploy
        uses: actions/upload-artifact@v4
        with:
          name: ebconfig
          path: |
            frontend/.elasticbeanstalk/config.yml
            frontend/Dockerrun.aws.json

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ebconfig
          path: .

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - run: sed -i "s|<AWS_ACCOUNT_ID>|${{ secrets.AWS_ACCOUNT_ID }}|" Dockerrun.aws.json
      - run: sed -i "s|<PROJECT_NAME>|conchayoro|" Dockerrun.aws.json
      - run: sed -i "s|<MODULE_NAME>|frontend|" Dockerrun.aws.json
      - run: sed -i "s|<TAG>|latest|" Dockerrun.aws.json

      - name: Verifica conteúdo final do Dockerrun
        run: cat Dockerrun.aws.json

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - run: python -m pip install --upgrade pip && pip install awsebcli

      - name: Realiza o deploy
        run: eb deploy --verbose --label "auto-${{ github.run_number }}"
