name: Provision ECR & EB
on:
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest
    env:
      AWS_REGION:   ${{ vars.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      BUCKET_S3:    ${{ vars.BUCKET_S3 }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.4.0"
      - run: |
          terraform -chdir=.environment init \
            -backend-config="bucket=${{ env.BUCKET_S3 }}" \
            -backend-config="key=state/terraform.tfstate"
      - run: terraform -chdir=.environment plan -var-file=terraform.tfvars
      - run: terraform -chdir=.environment apply -var-file=terraform.tfvars -auto-approve